version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    rebase-strategy: disabled
  - package-ecosystem: docker
    directory: /src/main/resources/database
    schedule:
      interval: weekly
    rebase-strategy: disabled
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    rebase-strategy: disabled
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    rebase-strategy: disabled
