#!/usr/bin/env python3

import subprocess
import os

arquivos_modificados = subprocess.check_output('git diff --cached --name-only', shell=True).decode('utf-8')

if 'windows' in os.name.lower():
    comando = r'.\gradlew.bat'
else:
    comando = './gradlew'

subprocess.run([comando, 'spotlessApply'])
subprocess.run(['git', 'add', arquivos_modificados])

