spring:
  thymeleaf:
    cache: false
  web:
    resources:
      static-locations:
        - "file:src/main/resources/static"
        - "classpath:/static/"
  mandatory-file-encoding: UTF-8
  output:
    ansi:
      enabled: always
  datasource:
    hikari:
      minimum-idle: 0
      initialization-fail-timeout: -1
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  sql:
    init:
      continue-on-error: true


logging:
  charset:
    console: UTF-8
    file: UTF-8
  level:
    root: INFO
    org:
      hibernate: INFO
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"
    dateformat: E MMM dd hh:mm:ss z yy

server:
  error:
    include-exception: true
    include-message: always
    include-binding-errors: always
