spring:
  mandatory-file-encoding: UTF-8
  output:
    ansi:
      enabled: always

logging:
  charset:
    console: UTF-8
    file: UTF-8
  level:
    org:
      hibernate: ERROR
  pattern:
    console:
    dateformat: E MMM dd hh:mm:ss z yy