spring:
  thymeleaf:
    cache: false
  web:
    resources:
      static-locations:
        - "file:src/main/resources/static"
        - "classpath:/static/"
  mandatory-file-encoding: UTF-8
  output:
    ansi:
      enabled: always

logging:
  charset:
    console: UTF-8
    file: UTF-8
  level:
    root: INFO
    org:
      hibernate: DEBUG
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    dateformat: E MMM dd hh:mm:ss z yy
