spring:
  mandatory-file-encoding: UTF-8
  output:
    ansi:
      enabled: always

  datasource:
    hikari:
      minimum-idle: 0
      initialization-fail-timeout: -1

  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      continue-on-error: true


logging:
  charset:
    console: UTF-8
    file: UTF-8
  level:
    org:
      hibernate: ERROR
  pattern:
    console:
    dateformat: E MMM dd hh:mm:ss z yy
