services:
  mysql-server:
    image: mysql:9.0.1
    container_name: diagrama-mysql
    restart: always
    environment:
      - LANG=C.UTF-8
      - MYSQL_DATABASE=db_HeberModelo
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - "mysql-volume:/var/lib/mysql"
      - "./init:/docker-entrypoint-initdb.d"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb_unicode_ci

volumes:
  mysql-volume:
    driver: local
