name: ci

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  tests:
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Setup Java
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '24'
          distribution: 'corretto'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Run tests
        run: ./gradlew test

  build:
    permissions:
      contents: write

    runs-on: ubuntu-22.04
    needs: tests
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Setup Java
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '24'
          distribution: 'corretto'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Setup Node
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 'latest'
      - name: Download dependencies
        run: npm ci
      - name: Compile SCSS
        run: npm run compile-scss
      - name: Compile Typescript
        run: npm run compile-ts
      - name: Minify Javascript
        run: npm run minify-js
      - name: Create jar file
        run: ./gradlew bootJar
      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          path: ./build/libs/heber-modelo.jar
          name: heber-modelo.jar

  create-release:
    permissions:
      contents: write

    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: actions/download-artifact@v5.0.0
        with:
          name: heber-modelo.jar

      - name: Calculate Checksum
        run: sha256sum heber-modelo.jar > SHA256SUM

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            SHA256SUM
            heber-modelo.jar
          make_latest: true
