name: ci

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags') && github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Setup Java
        uses: actions/setup-java@v4.6.0
        with:
          java-version: '23'
          distribution: 'corretto'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Setup Node
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 'latest'
      - name: Download dependencies
        run: npm ci
      - name: Compile SCSS
        run: npm run compile-scss
      - name: Compile Typescript
        run: npm run compile-ts
      - name: Create jar file
        run: ./gradlew bootJar
      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          path: ./build/libs/heber-modelo.jar
          name: heber-modelo.jar
  
  create-release:
    permissions:
      contents: write

    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/download-artifact@v4.1.8
        with:
          name: heber-modelo.jar

      - name: Calculate Checksum
        run: sha256sum heber-modelo.jar > SHA256SUM

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            SHA256SUM
            heber-modelo.jar
          make_latest: true
